"""Public deployment-contract API.

The package is deliberately independent from service startup and provider
configuration so manifests can be checked without initialising a runtime.
"""

from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .ppctl import (
        PPCTL_HTTP_SCHEMA_VERSION,
        PPCTL_SCHEMA_VERSION,
        Ppctl,
        PpctlHttpAdapter,
        create_ppctl_app,
    )

from .catalog import (
    DeploymentModule,
    DeploymentProfile,
    ResourcePolicy,
    deployment_modules,
    stable_profile_ids,
    stable_profiles,
)
from .container_artifacts import (
    COMPUTE_VARIANT_CPU,
    COMPUTE_VARIANT_CUDA,
    CONTAINER_ARTIFACT_BUNDLE_SCHEMA_VERSION,
    CONTAINER_ARTIFACT_EVIDENCE_SCHEMA_VERSION,
    CONTAINER_ARTIFACT_RECIPE_POLICY_SCHEMA_VERSION,
    CONTAINER_ARTIFACT_SCHEMA_VERSION,
    OCI_BASE_IMAGE_CATALOG_SCHEMA_VERSION,
    STANDARD_VARIANT,
    ArtifactBuildExecutor,
    ArtifactBuildPlan,
    ArtifactBundle,
    ArtifactCollaborationSurface,
    ArtifactDescriptor,
    ArtifactEvidenceReceipt,
    ArtifactInspectionReceipt,
    ArtifactMaterialization,
    ArtifactMount,
    ArtifactRequest,
    BaseImageIdentity,
    ContainerArtifactCompiler,
    ContainerArtifactError,
    RecipePolicyReceipt,
    RecipeSourceDigest,
    StaticRecipePolicyValidator,
)
from .controller import (
    DeploymentApplyError,
    DeploymentApplyResult,
    DeploymentController,
    DeploymentPreflight,
    DeploymentStatus,
    HostDiskUsage,
)
from .deployment_center import (
    DEPLOYMENT_CENTER_INSPECTION_SCHEMA_VERSION,
    DEPLOYMENT_CENTER_PREVIEW_SCHEMA_VERSION,
    DEPLOYMENT_CENTER_SCHEMA_VERSION,
    ControllerState,
    ControllerStateAdapter,
    DeploymentCenter,
    DeploymentCenterError,
    DeploymentInspection,
    DeploymentPreview,
    DeploymentPreviewRequest,
    EndpointContractGate,
    EnrollmentReadiness,
    HostInspection,
    HostInspector,
    HostStorage,
    InstallationResolution,
    InstallationResolver,
    ManifestDiff,
    ManifestTopologyProjection,
    ModelIdentityGate,
    ProfileRecommendation,
    StoragePreflight,
    UpdateClassification,
)
from .endpoint_contract import (
    DEPLOYMENT_MANIFEST_V2_SCHEMA_VERSION,
    DEPLOYMENT_RECEIPT_SCHEMA_VERSION,
    ENDPOINT_CONTRACT_SCHEMA_VERSION,
    MANIFEST_REVISION_SCHEMA_VERSION,
    PP_COMPUTE_NODE,
    PP_LOCAL_EDGE,
    PP_SERVER_BACKEND,
    AcceleratorResource,
    CapabilityBinding,
    CapabilityLeaseBinding,
    CapabilityResourceBinding,
    ComputeCompletionDecision,
    ComputeFence,
    ComputeLease,
    ComputeResult,
    DeploymentReceipt,
    EmbeddingIdentity,
    EndpointAdmission,
    EndpointAuthority,
    EndpointAuthorityProfile,
    EndpointBinding,
    EndpointCapability,
    EndpointContractError,
    EndpointContractRegistry,
    EndpointDeclaration,
    EndpointHeartbeat,
    EndpointHello,
    EndpointIdentityEvidence,
    EndpointManifestV2,
    EndpointObservation,
    EndpointProtocol,
    EndpointRequirement,
    EndpointResourceReport,
    GoldenProbeBinding,
    ManifestRevisionRecord,
    RerankIdentity,
    ResolvedEndpointDeploymentPlan,
    ResourceBudgetEvidence,
    ResourceLocationReferences,
    admit_endpoint,
    parse_deployment_manifest_v2,
    resolve_deployment_manifest_v2,
    validate_compute_exchange,
)
from .manifest import (
    DEPLOYMENT_MANIFEST_SCHEMA_VERSION,
    DeploymentContractError,
    DeploymentNode,
    ResolvedDeployment,
    ResourceBudget,
    ResourceLocations,
    load_deployment_manifest,
    resolve_deployment_manifest,
)
from .migration_journal import (
    DEFAULT_MIGRATION_LEASE_SECONDS,
    MIGRATION_JOURNAL_SCHEMA_VERSION,
    InMemoryMigrationExecutionJournal,
    MigrationExecutionIdentity,
    MigrationExecutionJournal,
    MigrationExecutionLease,
    MigrationJournalError,
    SQLiteMigrationExecutionJournal,
    migration_journal_schema_present,
)
from .plan import (
    DEPLOYMENT_OPERATIONS,
    DEPLOYMENT_PLAN_SCHEMA_VERSION,
    DeploymentPlan,
    DeploymentTarget,
    SQLiteAssetSnapshot,
    create_deployment_plan,
    create_install_plan,
    deployment_state_fingerprint,
    plan_drift_code,
    sqlite_asset_snapshot,
)
from .release_bundle import (
    ARTIFACT_BUNDLE_BINDING_SCHEMA_VERSION,
    MODEL_CATALOG_SCHEMA_VERSION,
    MODEL_RUNTIME_CLOUD,
    MODEL_RUNTIME_LOCAL,
    MODEL_RUNTIME_REMOTE,
    RELEASE_BUNDLE_SCHEMA_VERSION,
    RELEASE_EVIDENCE_SCHEMA_VERSION,
    ArtifactBundleBinding,
    ImmutableArtifactBinding,
    ModelCatalog,
    ModelResourceEstimate,
    ReleaseBundle,
    ReleaseBundleError,
    ReleaseBundleIdentity,
    VerifiedEvidenceProjection,
    canonical_model_catalog_bytes,
    canonical_release_bundle_bytes,
)
from .sqlite_migrations import (
    MIGRATION_EXECUTION_JOURNAL_MIGRATION_ID,
    NODE_GOVERNANCE_SCHEMA_VERSION,
    NODE_GOVERNANCE_V2_MIGRATION_ID,
)

__all__ = [
    "DEPLOYMENT_MANIFEST_V2_SCHEMA_VERSION",
    "DEPLOYMENT_MANIFEST_SCHEMA_VERSION",
    "DEPLOYMENT_CENTER_INSPECTION_SCHEMA_VERSION",
    "DEPLOYMENT_CENTER_PREVIEW_SCHEMA_VERSION",
    "DEPLOYMENT_CENTER_SCHEMA_VERSION",
    "DEPLOYMENT_OPERATIONS",
    "DEPLOYMENT_PLAN_SCHEMA_VERSION",
    "DEPLOYMENT_RECEIPT_SCHEMA_VERSION",
    "ENDPOINT_CONTRACT_SCHEMA_VERSION",
    "MANIFEST_REVISION_SCHEMA_VERSION",
    "PPCTL_SCHEMA_VERSION",
    "PPCTL_HTTP_SCHEMA_VERSION",
    "CONTAINER_ARTIFACT_BUNDLE_SCHEMA_VERSION",
    "CONTAINER_ARTIFACT_EVIDENCE_SCHEMA_VERSION",
    "CONTAINER_ARTIFACT_RECIPE_POLICY_SCHEMA_VERSION",
    "CONTAINER_ARTIFACT_SCHEMA_VERSION",
    "OCI_BASE_IMAGE_CATALOG_SCHEMA_VERSION",
    "MODEL_CATALOG_SCHEMA_VERSION",
    "ARTIFACT_BUNDLE_BINDING_SCHEMA_VERSION",
    "RELEASE_EVIDENCE_SCHEMA_VERSION",
    "RELEASE_BUNDLE_SCHEMA_VERSION",
    "COMPUTE_VARIANT_CPU",
    "COMPUTE_VARIANT_CUDA",
    "MODEL_RUNTIME_CLOUD",
    "MODEL_RUNTIME_LOCAL",
    "MODEL_RUNTIME_REMOTE",
    "STANDARD_VARIANT",
    "ArtifactBuildExecutor",
    "ArtifactBuildPlan",
    "ArtifactBundle",
    "ArtifactCollaborationSurface",
    "ArtifactDescriptor",
    "ArtifactEvidenceReceipt",
    "ArtifactInspectionReceipt",
    "ArtifactMaterialization",
    "ArtifactMount",
    "ArtifactRequest",
    "BaseImageIdentity",
    "ContainerArtifactCompiler",
    "ContainerArtifactError",
    "RecipePolicyReceipt",
    "RecipeSourceDigest",
    "StaticRecipePolicyValidator",
    "ArtifactBundleBinding",
    "ImmutableArtifactBinding",
    "ModelCatalog",
    "ModelResourceEstimate",
    "ReleaseBundle",
    "ReleaseBundleError",
    "ReleaseBundleIdentity",
    "VerifiedEvidenceProjection",
    "PP_COMPUTE_NODE",
    "PP_LOCAL_EDGE",
    "PP_SERVER_BACKEND",
    "AcceleratorResource",
    "CapabilityBinding",
    "CapabilityLeaseBinding",
    "CapabilityResourceBinding",
    "ComputeCompletionDecision",
    "ComputeFence",
    "ComputeLease",
    "ComputeResult",
    "DeploymentReceipt",
    "EmbeddingIdentity",
    "EndpointAdmission",
    "EndpointAuthority",
    "EndpointAuthorityProfile",
    "EndpointBinding",
    "EndpointCapability",
    "EndpointContractError",
    "EndpointContractRegistry",
    "EndpointDeclaration",
    "EndpointHeartbeat",
    "EndpointHello",
    "EndpointIdentityEvidence",
    "EndpointManifestV2",
    "EndpointObservation",
    "EndpointProtocol",
    "EndpointRequirement",
    "EndpointResourceReport",
    "GoldenProbeBinding",
    "ManifestRevisionRecord",
    "ResolvedEndpointDeploymentPlan",
    "ResourceBudgetEvidence",
    "ResourceLocationReferences",
    "RerankIdentity",
    "DeploymentContractError",
    "DeploymentApplyError",
    "DeploymentApplyResult",
    "DeploymentCenter",
    "DeploymentCenterError",
    "DeploymentController",
    "DeploymentInspection",
    "DeploymentModule",
    "DeploymentNode",
    "DeploymentPlan",
    "DeploymentPreflight",
    "DeploymentStatus",
    "DeploymentProfile",
    "DeploymentPreview",
    "DeploymentPreviewRequest",
    "DeploymentTarget",
    "SQLiteAssetSnapshot",
    "ResolvedDeployment",
    "ResourceBudget",
    "ResourceLocations",
    "ResourcePolicy",
    "HostDiskUsage",
    "HostInspection",
    "HostInspector",
    "HostStorage",
    "InstallationResolution",
    "InstallationResolver",
    "ControllerState",
    "ControllerStateAdapter",
    "EndpointContractGate",
    "EnrollmentReadiness",
    "ModelIdentityGate",
    "ManifestDiff",
    "ManifestTopologyProjection",
    "Ppctl",
    "PpctlHttpAdapter",
    "ProfileRecommendation",
    "StoragePreflight",
    "UpdateClassification",
    "NODE_GOVERNANCE_SCHEMA_VERSION",
    "NODE_GOVERNANCE_V2_MIGRATION_ID",
    "deployment_modules",
    "admit_endpoint",
    "create_install_plan",
    "create_ppctl_app",
    "create_deployment_plan",
    "deployment_state_fingerprint",
    "load_deployment_manifest",
    "resolve_deployment_manifest",
    "plan_drift_code",
    "parse_deployment_manifest_v2",
    "resolve_deployment_manifest_v2",
    "sqlite_asset_snapshot",
    "stable_profile_ids",
    "stable_profiles",
    "validate_compute_exchange",
    "canonical_model_catalog_bytes",
    "canonical_release_bundle_bytes",
    "APPLY_PHASES",
    "ROLLBACK_PHASES",
    "CanonicalStateMigrationAdapter",
    "CanonicalStateObservation",
    "DerivedGenerationObservation",
    "DerivedIndexMigrationAdapter",
    "EdgeComputeMigrationAdapter",
    "ExecutionGrant",
    "MaintenanceMigrationAdapter",
    "MigrationAdapters",
    "MigrationApplyResult",
    "MigrationExecutionContext",
    "MigrationExecutionGrant",
    "MigrationExecutionIdentity",
    "MigrationExecutionJournal",
    "MigrationExecutionLease",
    "MigrationJournalError",
    "InMemoryMigrationExecutionJournal",
    "SQLiteMigrationExecutionJournal",
    "MIGRATION_JOURNAL_SCHEMA_VERSION",
    "MIGRATION_EXECUTION_JOURNAL_MIGRATION_ID",
    "DEFAULT_MIGRATION_LEASE_SECONDS",
    "migration_journal_schema_present",
    "MigrationGrant",
    "MigrationIntent",
    "MigrationObservations",
    "MigrationOperationPlan",
    "MigrationPlan",
    "MigrationOperations",
    "MigrationOperationsError",
    "MigrationObservationAdapter",
    "MigrationPhaseRecord",
    "MigrationPreflight",
    "NodeReadinessObservation",
    "RetentionCacheMigrationAdapter",
    "RuntimeMigrationAdapter",
    "RuntimeObservation",
    "TopologyDigest",
    "compose_production_migration_operations",
]

_PPCTL_EXPORTS = frozenset(
    {
        "PPCTL_HTTP_SCHEMA_VERSION",
        "PPCTL_SCHEMA_VERSION",
        "Ppctl",
        "PpctlHttpAdapter",
        "create_ppctl_app",
    }
)

_MIGRATION_OPERATION_EXPORTS = frozenset(
    {
        "APPLY_PHASES",
        "ROLLBACK_PHASES",
        "CanonicalStateMigrationAdapter",
        "CanonicalStateObservation",
        "DerivedGenerationObservation",
        "DerivedIndexMigrationAdapter",
        "EdgeComputeMigrationAdapter",
        "ExecutionGrant",
        "MaintenanceMigrationAdapter",
        "MigrationAdapters",
        "MigrationApplyResult",
        "MigrationExecutionContext",
        "MigrationExecutionGrant",
        "MigrationGrant",
        "MigrationIntent",
        "MigrationObservationAdapter",
        "MigrationObservations",
        "MigrationOperationPlan",
        "MigrationOperations",
        "MigrationOperationsError",
        "MigrationPhaseRecord",
        "MigrationPlan",
        "MigrationPreflight",
        "NodeReadinessObservation",
        "RetentionCacheMigrationAdapter",
        "RuntimeMigrationAdapter",
        "RuntimeObservation",
        "TopologyDigest",
        "compose_production_migration_operations",
    }
)


def __getattr__(name: str) -> object:
    """Load the optional HTTP adapter only when a caller requests it.

    The build-policy tools intentionally install only their policy parser.
    Keeping Starlette behind this narrow public-API seam lets those tools
    validate static recipes without initialising the HTTP adapter, while
    preserving the existing ``plastic_promise.deployment`` exports for
    runtime callers.
    """

    if name in _MIGRATION_OPERATION_EXPORTS:
        module_name = (
            ".production_migration"
            if name == "compose_production_migration_operations"
            else ".migration_operations"
        )
        value = getattr(import_module(module_name, __name__), name)
        globals()[name] = value
        return value
    if name not in _PPCTL_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(".ppctl", __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Expose lazy public names to interactive API discovery."""

    return sorted({*globals(), *_PPCTL_EXPORTS, *_MIGRATION_OPERATION_EXPORTS})
