"""Platform activation assets rendered by the bounded deployment installer.

The controller writes these files but never registers, enables, starts or stops
an operating-system service.  This preserves the interactive-TTY/sudo boundary
while making ``install`` materially prepare the selected runtime instead of
leaving only an abstract descriptor behind.
"""

from __future__ import annotations

import platform
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING
from xml.sax.saxutils import escape as xml_escape

from ._json_io import write_text_atomically

if TYPE_CHECKING:
    from .plan import DeploymentPlan


@dataclass(frozen=True)
class RuntimeAsset:
    """One exact controller-owned activation asset for a selected module."""

    relative_path: Path
    content: str


def runtime_asset_directory(plan: DeploymentPlan, module_id: str) -> Path:
    """Return the precise installer-owned directory for one module's files."""

    return plan.target.state_root / "runtime-assets" / module_id


def _compose_content() -> str:
    """Render a no-secret, no-pull node Compose contract.

    ``pull_policy: never`` is intentional: an activation asset must not bypass
    the reviewed preflight by downloading an image.  Operators pre-load a fixed
    image digest after preflight, then explicitly activate the generated asset.
    """

    return """# Generated by plastic-promise-deploy; do not add credentials here.
services:
  local-inference-node:
    image: \"${PP_LOCAL_NODE_IMAGE:?set a fixed image digest}\"
    pull_policy: never
    network_mode: host
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    gpus: all
    environment:
      TZ: \"UTC\"
      PP_ENDPOINT_ROLE: \"pp-compute-node\"
      PP_LOCAL_NODE_BIND_HOST: \"127.0.0.1\"
      PP_LOCAL_NODE_PORT: \"19130\"
      PP_LOCAL_NODE_MAX_CONCURRENCY: \"${PP_LOCAL_NODE_MAX_CONCURRENCY:-1}\"
      PP_LOCAL_NODE_ID: \"${PP_LOCAL_NODE_ID:?set a non-secret node ID}\"
      PP_LOCAL_NODE_PROVIDER_MODE: \"${PP_LOCAL_NODE_PROVIDER_MODE:-local}\"
      PP_LOCAL_NODE_EMBEDDING_BACKEND: \"${PP_LOCAL_NODE_EMBEDDING_BACKEND:-llama.cpp}\"
      PP_LOCAL_NODE_EMBEDDING_MODEL: \"${PP_LOCAL_NODE_EMBEDDING_MODEL:?set model identity}\"
      PP_LOCAL_NODE_EMBEDDING_REVISION: \"${PP_LOCAL_NODE_EMBEDDING_REVISION:?set a fixed revision}\"
      PP_LOCAL_NODE_EMBEDDING_DIMENSION: \"${PP_LOCAL_NODE_EMBEDDING_DIMENSION:?set output dimension}\"
      PP_LOCAL_NODE_EMBEDDING_NORMALIZATION: \"${PP_LOCAL_NODE_EMBEDDING_NORMALIZATION:?set normalization}\"
      PP_LOCAL_NODE_EMBEDDING_MODEL_REFERENCE: \"${PP_LOCAL_NODE_EMBEDDING_MODEL_REFERENCE:-/models/embedding}\"
      PP_LOCAL_NODE_CLOUD_API_KEY: \"${PP_LOCAL_NODE_CLOUD_API_KEY:-}\"
      PP_LOCAL_NODE_EMBEDDING_CLOUD_BASE_URL: \"${PP_LOCAL_NODE_EMBEDDING_CLOUD_BASE_URL:-}\"
      PP_LOCAL_NODE_EMBEDDING_CLOUD_PATH: \"${PP_LOCAL_NODE_EMBEDDING_CLOUD_PATH:-/embeddings}\"
      PP_LOCAL_NODE_EMBEDDING_LLAMA_CPP_BASE_URL: \"${PP_LOCAL_NODE_EMBEDDING_LLAMA_CPP_BASE_URL:-http://127.0.0.1:19131}\"
      PP_LOCAL_NODE_EMBEDDING_LLAMA_CPP_PATH: \"${PP_LOCAL_NODE_EMBEDDING_LLAMA_CPP_PATH:-/v1/embeddings}\"
      PP_LOCAL_NODE_RERANK_BACKEND: \"${PP_LOCAL_NODE_RERANK_BACKEND:-llama.cpp}\"
      PP_LOCAL_NODE_RERANK_MODEL: \"${PP_LOCAL_NODE_RERANK_MODEL:?set model identity}\"
      PP_LOCAL_NODE_RERANK_REVISION: \"${PP_LOCAL_NODE_RERANK_REVISION:?set a fixed revision}\"
      PP_LOCAL_NODE_RERANK_MODEL_REFERENCE: \"${PP_LOCAL_NODE_RERANK_MODEL_REFERENCE:-/models/rerank}\"
      PP_LOCAL_NODE_RERANK_CLOUD_BASE_URL: \"${PP_LOCAL_NODE_RERANK_CLOUD_BASE_URL:-}\"
      PP_LOCAL_NODE_RERANK_CLOUD_PATH: \"${PP_LOCAL_NODE_RERANK_CLOUD_PATH:-/rerank}\"
      PP_LOCAL_NODE_RERANK_LLAMA_CPP_BASE_URL: \"${PP_LOCAL_NODE_RERANK_LLAMA_CPP_BASE_URL:-http://127.0.0.1:19132}\"
      PP_LOCAL_NODE_RERANK_LLAMA_CPP_PATH: \"${PP_LOCAL_NODE_RERANK_LLAMA_CPP_PATH:-/rerank}\"
      PP_LOCAL_NODE_STRUCTURED_JSON_BACKEND: \"${PP_LOCAL_NODE_STRUCTURED_JSON_BACKEND:-off}\"
      PP_LOCAL_NODE_STRUCTURED_JSON_MODEL: \"${PP_LOCAL_NODE_STRUCTURED_JSON_MODEL:-}\"
      PP_LOCAL_NODE_STRUCTURED_JSON_REVISION: \"${PP_LOCAL_NODE_STRUCTURED_JSON_REVISION:-}\"
      PP_LOCAL_NODE_STRUCTURED_JSON_CLOUD_BASE_URL: \"${PP_LOCAL_NODE_STRUCTURED_JSON_CLOUD_BASE_URL:-}\"
      PP_LOCAL_NODE_STRUCTURED_JSON_CLOUD_PATH: \"${PP_LOCAL_NODE_STRUCTURED_JSON_CLOUD_PATH:-/chat/completions}\"
      PP_LOCAL_NODE_MODEL_CACHE_DIR: \"/models\"
    volumes:
      - type: bind
        source: \"${PP_LOCAL_NODE_MODEL_DIRECTORY:?set a pre-populated model directory}\"
        target: /models
        read_only: true
      - type: bind
        source: \"${PP_LOCAL_NODE_RUNTIME_DIRECTORY:?set a node-local runtime directory}\"
        target: /var/lib/plastic-promise/local-inference-node
    tmpfs:
      - /tmp:rw,exec,nosuid,size=512m
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: \"3\"
"""


def _systemd_content(asset_directory: Path) -> str:
    directory = str(asset_directory)
    return f"""# Generated by plastic-promise-deploy; installation does not enable this unit.
[Unit]
Description=Plastic Promise local inference node (Compose)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
WorkingDirectory={directory}
EnvironmentFile=-{directory}/local-inference-node.env
ExecStart=/usr/bin/env docker compose --project-name plastic-promise-local-inference-node --env-file {directory}/local-inference-node.env -f {directory}/compose.yaml up --no-build
ExecStop=/usr/bin/env docker compose --project-name plastic-promise-local-inference-node --env-file {directory}/local-inference-node.env -f {directory}/compose.yaml down
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true

[Install]
WantedBy=default.target
"""


def _canonical_systemd_content(asset_directory: Path) -> str:
    environment_file = asset_directory / "canonical-runtime.env"
    return f"""# Generated by plastic-promise-deploy; installation does not enable this unit.
[Unit]
Description=Plastic Promise canonical MCP runtime
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
EnvironmentFile={environment_file}
ExecStart=/usr/bin/env plastic-promise-canonical-runtime
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true

[Install]
WantedBy=default.target
"""


def _launchd_content(asset_directory: Path) -> str:
    directory = str(asset_directory)
    arguments = (
        "/usr/bin/env",
        "docker",
        "compose",
        "--project-name",
        "plastic-promise-local-inference-node",
        "--env-file",
        f"{directory}/local-inference-node.env",
        "-f",
        f"{directory}/compose.yaml",
        "up",
        "--no-build",
    )
    rendered_arguments = "\n".join(
        f"    <string>{xml_escape(value)}</string>" for value in arguments
    )
    return f"""<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
  <key>Label</key>
  <string>org.plastic-promise.local-inference-node</string>
  <key>ProgramArguments</key>
  <array>
{rendered_arguments}
  </array>
  <key>WorkingDirectory</key>
  <string>{xml_escape(directory)}</string>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
"""


def _canonical_launchd_content(plan: DeploymentPlan) -> str:
    database_path = xml_escape(str(plan.target.database_path))
    lancedb_path = xml_escape(str(plan.target.state_root / "lancedb"))
    return f"""<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
  <key>Label</key>
  <string>org.plastic-promise.canonical-runtime</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/env</string>
    <string>plastic-promise-canonical-runtime</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>TZ</key>
    <string>UTC</string>
    <key>PLASTIC_DB_PATH</key>
    <string>{database_path}</string>
    <key>PLASTIC_LANCEDB_PATH</key>
    <string>{lancedb_path}</string>
  </dict>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
"""


def _windows_script_content() -> str:
    return """# Generated by plastic-promise-deploy; explicit invocation only.
param(
    [ValidateSet(\"start\", \"stop\", \"status\")]
    [string]$Action = \"status\"
)

$AssetRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$ComposeFile = Join-Path $AssetRoot \"compose.yaml\"
$EnvironmentFile = Join-Path $AssetRoot \"local-inference-node.env\"

switch ($Action) {
    \"start\" {
        & docker compose --project-name plastic-promise-local-inference-node --env-file $EnvironmentFile -f $ComposeFile up --no-build
    }
    \"stop\" {
        & docker compose --project-name plastic-promise-local-inference-node --env-file $EnvironmentFile -f $ComposeFile down
    }
    \"status\" {
        & docker compose --project-name plastic-promise-local-inference-node --env-file $EnvironmentFile -f $ComposeFile ps
    }
}

exit $LASTEXITCODE
"""


def _canonical_windows_script_content(plan: DeploymentPlan) -> str:
    database_path = str(plan.target.database_path).replace("'", "''")
    lancedb_path = str(plan.target.state_root / "lancedb").replace("'", "''")
    return f"""# Generated by plastic-promise-deploy; explicit invocation only.
$env:TZ = 'UTC'
$env:PLASTIC_DB_PATH = '{database_path}'
$env:PLASTIC_LANCEDB_PATH = '{lancedb_path}'
& plastic-promise-canonical-runtime
exit $LASTEXITCODE
"""


def _canonical_environment_content(plan: DeploymentPlan) -> str:
    """Render environment values as a non-secret systemd-compatible file."""

    def quoted(value: Path) -> str:
        return str(value).replace("\\", "\\\\").replace('"', '\\"')

    return (
        'TZ="UTC"\n'
        f'PLASTIC_DB_PATH="{quoted(plan.target.database_path)}"\n'
        f'PLASTIC_LANCEDB_PATH="{quoted(plan.target.state_root / "lancedb")}"\n'
    )


def _canonical_runtime_assets(plan: DeploymentPlan, system_name: str) -> tuple[RuntimeAsset, ...]:
    environment = RuntimeAsset(Path("canonical-runtime.env"), _canonical_environment_content(plan))
    if system_name == "Windows":
        return (
            environment,
            RuntimeAsset(
                Path("start-plastic-promise-runtime.ps1"),
                _canonical_windows_script_content(plan),
            ),
        )
    if system_name == "Darwin":
        return (
            environment,
            RuntimeAsset(
                Path("org.plastic-promise.canonical-runtime.plist"),
                _canonical_launchd_content(plan),
            ),
        )
    return (
        environment,
        RuntimeAsset(
            Path("plastic-promise-canonical-runtime.service"),
            _canonical_systemd_content(runtime_asset_directory(plan, "canonical-runtime")),
        ),
    )


def runtime_assets_for_module(
    plan: DeploymentPlan,
    module_id: str,
    *,
    system_name: str | None = None,
) -> tuple[RuntimeAsset, ...]:
    """Build exact platform assets for modules with an executable runtime."""

    selected_system = platform.system() if system_name is None else system_name
    if module_id == "canonical-runtime":
        return _canonical_runtime_assets(plan, selected_system)
    if module_id != "heterogeneous-inference-node":
        return ()
    asset_directory = runtime_asset_directory(plan, module_id)
    assets = [RuntimeAsset(Path("compose.yaml"), _compose_content())]
    if selected_system == "Windows":
        assets.append(
            RuntimeAsset(Path("start-local-inference-node.ps1"), _windows_script_content())
        )
    elif selected_system == "Darwin":
        assets.append(
            RuntimeAsset(
                Path("org.plastic-promise.local-inference-node.plist"),
                _launchd_content(asset_directory),
            )
        )
    else:
        assets.append(
            RuntimeAsset(
                Path("plastic-promise-local-inference-node-compose.service"),
                _systemd_content(asset_directory),
            )
        )
    return tuple(assets)


def materialize_runtime_assets(plan: DeploymentPlan, module_id: str) -> tuple[Path, ...]:
    """Write only the exact controller-owned assets for one selected module."""

    root = runtime_asset_directory(plan, module_id)
    assets = runtime_assets_for_module(plan, module_id)
    for asset in assets:
        write_text_atomically(root / asset.relative_path, asset.content)
    return tuple(asset.relative_path for asset in assets)


def remove_runtime_assets(plan: DeploymentPlan, module_id: str) -> None:
    """Remove generated files only, retaining any unrelated user files."""

    root = runtime_asset_directory(plan, module_id)
    generated_paths = {
        asset.relative_path
        for system_name in ("Linux", "Darwin", "Windows")
        for asset in runtime_assets_for_module(plan, module_id, system_name=system_name)
    }
    for relative_path in generated_paths:
        try:
            (root / relative_path).unlink()
        except FileNotFoundError:
            continue
    try:
        root.rmdir()
        root.parent.rmdir()
    except OSError:
        pass


__all__ = [
    "RuntimeAsset",
    "materialize_runtime_assets",
    "remove_runtime_assets",
    "runtime_asset_directory",
    "runtime_assets_for_module",
]
