"""Plastic Promise 核心基础层

包含:
- constants: 九大系统、三层防线、信任分、审计维度、11条核心原则、SCARF等全部常量
- context_engine: ContextEngine 上下文供应引擎（Python回退版 + Rust PyO3桥接）
"""

from plastic_promise.core.constants import (
    DIGITAL_BODY_SYSTEMS,
    DEFENSE_LAYERS,
    TRUST_INITIAL, TRUST_DECAY_RATE, TRUST_BOOST_RATE, TRUST_MIN, TRUST_MAX,
    AUDIT_DIMENSIONS,
    SCARF_DIMENSIONS,
    CONTEXT_LAYERS, RRF_K, SYMBOL_RULE_KEYWORDS, ASSOCIATION_WEIGHTS,
    MEMORY_TIERS, MEMORY_HEALTH_THRESHOLD, MEMORY_DECAY_THRESHOLD,
    MEMORY_GC_INTERVAL_DAYS,
    WORTH_SUCCESS_WEIGHT, WORTH_FAILURE_WEIGHT, WORTH_MIN_OBSERVATIONS,
    CORE_PRINCIPLES, PRINCIPLE_DOMAINS, PRINCIPLE_INHERITANCE_DIRECTIONS,
    PRINCIPLE_INHERITANCE_DECAY,
    CRON_CONFIG,
    CLASSIFIER_KEYWORDS, CLASSIFIER_THRESHOLD_CLAUDE, CLASSIFIER_THRESHOLD_ACP,
    CEI_THRESHOLDS, CEI_TARGET,
    PRE_CHECK_ALERT_THRESHOLD, CLOSURE_RATE_TARGET, PRINCIPLE_ACTIVATION_TARGET,
    INERTIA_SUPPRESSION_WINDOW, INERTIA_SUPPRESSION_THRESHOLD,
    CURIOSITY_EXPLORE_RATE,
)

from plastic_promise.core.context_engine import (
    ContextEngine,
    ContextPack,
    ContextItem,
)

__all__ = [
    "DIGITAL_BODY_SYSTEMS",
    "DEFENSE_LAYERS",
    "TRUST_INITIAL", "TRUST_DECAY_RATE", "TRUST_BOOST_RATE", "TRUST_MIN", "TRUST_MAX",
    "AUDIT_DIMENSIONS",
    "SCARF_DIMENSIONS",
    "CONTEXT_LAYERS", "RRF_K", "SYMBOL_RULE_KEYWORDS", "ASSOCIATION_WEIGHTS",
    "MEMORY_TIERS", "MEMORY_HEALTH_THRESHOLD", "MEMORY_DECAY_THRESHOLD",
    "MEMORY_GC_INTERVAL_DAYS",
    "WORTH_SUCCESS_WEIGHT", "WORTH_FAILURE_WEIGHT", "WORTH_MIN_OBSERVATIONS",
    "CORE_PRINCIPLES", "PRINCIPLE_DOMAINS", "PRINCIPLE_INHERITANCE_DIRECTIONS",
    "PRINCIPLE_INHERITANCE_DECAY",
    "CRON_CONFIG",
    "CLASSIFIER_KEYWORDS", "CLASSIFIER_THRESHOLD_CLAUDE", "CLASSIFIER_THRESHOLD_ACP",
    "CEI_THRESHOLDS", "CEI_TARGET",
    "PRE_CHECK_ALERT_THRESHOLD", "CLOSURE_RATE_TARGET", "PRINCIPLE_ACTIVATION_TARGET",
    "INERTIA_SUPPRESSION_WINDOW", "INERTIA_SUPPRESSION_THRESHOLD",
    "CURIOSITY_EXPLORE_RATE",
    "ContextEngine", "ContextPack", "ContextItem",
]
